#!/usr/bin/env python3
"""
STAGE 06c — Core Promoter Element Synergism & Co-occurrence Analysis

Performs pairwise co-occurrence and positional spacing analysis for core promoter elements:
- Scans promoters for TATA, Inr, DPE, MTE, and BRE motifs.
- Identifies pair co-occurrences (e.g., TATA-Inr, Inr-MTE, MTE-DPE, BRE-TATA, TATA-DPE).
- Evaluates real vs. randomized background co-occurrences.
- Generates a 4-panel figure: element multiplicity, pairwise co-occurrence
  heatmap, TSS-relative pair-density curves, and inter-element spacing curves.

FIXES (v2)
- Pair names: pair keys are generated by itertools.combinations over
  [TATA, Inr, DPE, MTE, BRE], i.e. "DPE-MTE" and "TATA-BRE". The plotting code
  asked for "MTE-DPE" and "BRE-TATA", which never matched, so those two curves
  were silently never drawn. resolve_pair() now accepts either order.
- Strands: motifs are scanned on BOTH strands (SCAN_BOTH_STRANDS), as 06b does.
  Previously only the + strand was scanned, so 06b and 06c disagreed on the
  same promoters.
- Density curves are skipped (with a note) when a pair has <2 distinct values
  instead of letting seaborn warn/fail.

NOTE ON DPE / MTE / Inr in UPSTREAM-ONLY promoters (-1000 to -1): canonically
these sit at/after the TSS, so here they are sequence-pattern matches judged
against the shuffled background, not positioned core elements; pair results
involving them should be read the same way.
"""

import os
import random
import re
import itertools
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

INPUT_FASTA = "outputs/promoter_sequences.fasta"
OUT_PLOT = "outputs/promoter_synergism_analysis.png"
OUT_REPORT = "outputs/promoter_synergism_report.txt"

random.seed(42)
np.random.seed(42)

# IUPAC ambiguity helper
IUPAC = {
    'A': 'A', 'C': 'C', 'G': 'G', 'T': 'T', 'R': '[AG]', 'Y': '[CT]',
    'S': '[GC]', 'W': '[AT]', 'K': '[GT]', 'M': '[AC]', 'B': '[CGT]',
    'D': '[AGT]', 'H': '[ACT]', 'V': '[ACG]', 'N': '[ACGT]'
}

def parse_iupac(pat):
    return re.compile("".join(IUPAC.get(b, b) for b in pat.upper()))

SCAN_BOTH_STRANDS = True   # match 06b, which scans + and - strands

COMPLEMENT = str.maketrans("ACGTN", "TGCAN")

def reverse_complement(seq):
    return seq.translate(COMPLEMENT)[::-1]

# Core 5 Promoter Motifs analyzed for synergism
CORE_5_MOTIFS = {
    "TATA": "TATAWAWR",
    "Inr":  "YYANWYY",
    "DPE":  "RGWCGY",
    "MTE":  "CSARCSS",
    "BRE":  "SSRRCGCC",
}

MOTIF_REGEX = {name: parse_iupac(seq) for name, seq in CORE_5_MOTIFS.items()}


def read_fasta(path):
    seqs = {}
    name = None
    if not os.path.exists(path):
        return seqs
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith(">"):
                name = line[1:].split()[0]
                seqs[name] = ""
            else:
                seqs[name] += line.upper()
    return seqs


def shuffle_sequence_composition(seqs_dict):
    """Generates randomized sequence controls matching base composition and length."""
    shuffled_dict = {}
    for name, seq in seqs_dict.items():
        chars = list(seq)
        random.shuffle(chars)
        shuffled_dict[name] = "".join(chars)
    return shuffled_dict


def scan_motif_positions(seq):
    """Finds starting positions (forward-strand coordinates) of all 5 core elements within a
    single promoter, on both strands when SCAN_BOTH_STRANDS is set."""
    positions = {}
    seq_len = len(seq)
    rev_seq = reverse_complement(seq) if SCAN_BOTH_STRANDS else None
    for name, regex in MOTIF_REGEX.items():
        matches = [m.start() for m in regex.finditer(seq)]
        if rev_seq is not None:
            for m in regex.finditer(rev_seq):
                matches.append(seq_len - m.start() - (m.end() - m.start()))
        if matches:
            positions[name] = sorted(matches)
    return positions


def resolve_pair(data_by_pair, pair):
    """Returns (key, values) for a pair given in EITHER order ("MTE-DPE" or "DPE-MTE"); the
    stored keys follow itertools.combinations order over CORE_5_MOTIFS. (None, []) if absent."""
    a, b = pair.split("-")
    for key in (f"{a}-{b}", f"{b}-{a}"):
        if key in data_by_pair:
            return key, data_by_pair[key]
    return None, []


def analyze_synergism(seqs_dict):
    """Analyzes element counts per promoter, co-occurrence matrices, and distance distributions."""
    total_seqs = len(seqs_dict)
    element_counts_per_promoter = []
    
    # Pairwise co-occurrence counts
    motif_names = list(CORE_5_MOTIFS.keys())
    co_occurrence_matrix = {m1: {m2: 0 for m2 in motif_names} for m1 in motif_names}
    
    # Distance distributions between motif pairs
    pair_distances = {f"{m1}-{m2}": [] for m1, m2 in itertools.combinations(motif_names, 2)}
    
    # Positional density of pairs relative to the TSS (TSS = end of the upstream-only sequence)
    pair_tss_positions = {f"{m1}-{m2}": [] for m1, m2 in itertools.combinations(motif_names, 2)}

    for seq_id, seq in seqs_dict.items():
        seq_len = len(seq)
        pos_dict = scan_motif_positions(seq)
        
        # Count unique core element types present in this promoter
        element_counts_per_promoter.append(len(pos_dict))
        
        # Matrix counts
        present_motifs = list(pos_dict.keys())
        for m1, m2 in itertools.combinations(present_motifs, 2):
            co_occurrence_matrix[m1][m2] += 1
            co_occurrence_matrix[m2][m1] += 1
            
            pair_key = f"{m1}-{m2}" if f"{m1}-{m2}" in pair_distances else f"{m2}-{m1}"
            
            # Calculate distance between closest instances of the two motifs
            min_dist = min(abs(p1 - p2) for p1 in pos_dict[m1] for p2 in pos_dict[m2])
            pair_distances[pair_key].append(min_dist)
            
            # Position relative to TSS: the promoter is upstream-only, so the TSS is the boundary right
            # after the last base (last base = -1). Anchoring on seq_len also stays correct for
            # promoters clipped shorter than 1000 bp at a contig edge.
            avg_pos = np.mean(pos_dict[m1] + pos_dict[m2]) - seq_len
            pair_tss_positions[pair_key].append(avg_pos)

    return {
        'total_seqs': total_seqs,
        'element_counts': element_counts_per_promoter,
        'matrix': co_occurrence_matrix,
        'distances': pair_distances,
        'tss_positions': pair_tss_positions
    }


def run_synergism_analysis():
    real_seqs = read_fasta(INPUT_FASTA)
    if not real_seqs:
        print(f"Error: FASTA file not found at '{INPUT_FASTA}'.")
        return

    n_promoters = len(real_seqs)
    print(f"Loaded {n_promoters} promoter sequences. Running Synergism Analysis...")

    rand_seqs = shuffle_sequence_composition(real_seqs)
    
    real_synergy = analyze_synergism(real_seqs)
    rand_synergy = analyze_synergism(rand_seqs)

    # 1. Report Output Generation
    report_lines = [
        f"CORE PROMOTER ELEMENT SYNERGISM REPORT ({n_promoters} Sequences)",
        "=" * 70,
        "\n1. ELEMENT COMBINATION FREQUENCY PER PROMOTER:",
    ]
    
    for i in range(6):
        cnt = real_synergy['element_counts'].count(i)
        pct = (cnt / n_promoters) * 100
        report_lines.append(f"  Promoters with {i} core elements: {cnt}/{n_promoters} ({pct:.1f}%)")

    report_lines.append("\n2. PAIRWISE CO-OCCURRENCE PERCENTAGES (REAL vs. RANDOM):")
    motif_names = list(CORE_5_MOTIFS.keys())
    for m1, m2 in itertools.combinations(motif_names, 2):
        pair_key = f"{m1}-{m2}"
        r_cnt = real_synergy['matrix'][m1][m2]
        rnd_cnt = rand_synergy['matrix'][m1][m2]
        r_pct = (r_cnt / n_promoters) * 100
        rnd_pct = (rnd_cnt / n_promoters) * 100
        report_lines.append(f"  {pair_key:<12}: Real={r_cnt} ({r_pct:.1f}%) | Random={rnd_cnt} ({rnd_pct:.1f}%)")

    os.makedirs("outputs", exist_ok=True)
    with open(OUT_REPORT, "w") as f:
        f.write("\n".join(report_lines))
    print("\n".join(report_lines))

    # 2. Multi-panel Visualization (Replicating Figure 5 Synergism Trends)
    fig = plt.figure(figsize=(16, 11))
    fig.suptitle("Synergism and Co-occurrence Analysis of Core Promoter Elements", fontsize=15, fontweight='bold')

    # Subplot A: Element Multiplicity Distribution (0 to 5 Elements)
    ax1 = fig.add_subplot(2, 2, 1)
    counts_real = [real_synergy['element_counts'].count(i) for i in range(6)]
    counts_rand = [rand_synergy['element_counts'].count(i) for i in range(6)]
    x = np.arange(6)
    w = 0.35
    ax1.bar(x - w/2, counts_real, w, label='Real Promoters (Dark)', color='navy')
    ax1.bar(x + w/2, counts_rand, w, label='Random Background (Light)', color='lightblue')
    ax1.set_xlabel('Number of Core Promoter Elements Present')
    ax1.set_ylabel('Number of Promoters')
    ax1.set_title('A. Number of Core Elements per Promoter')
    ax1.set_xticks(x)
    ax1.legend()
    ax1.grid(axis='y', linestyle='--', alpha=0.5)

    # Subplot B: Co-occurrence Heatmap Matrix (%)
    ax2 = fig.add_subplot(2, 2, 2)
    heatmap_data = np.zeros((5, 5))
    for i, m1 in enumerate(motif_names):
        for j, m2 in enumerate(motif_names):
            if i != j:
                heatmap_data[i, j] = (real_synergy['matrix'][m1][m2] / n_promoters) * 100
            else:
                heatmap_data[i, j] = np.nan  # Mask diagonal
                
    sns.heatmap(heatmap_data, annot=True, fmt=".1f", cmap="YlGnBu", 
                xticklabels=motif_names, yticklabels=motif_names, ax=ax2, cbar_kws={'label': '% Co-occurrence'})
    ax2.set_title('B. Core Element Pairwise Co-occurrence Matrix (%)')

    # Subplot C: Positional Co-occurrence Density Near TSS (Figure 5 Peak Replication)
    ax3 = fig.add_subplot(2, 2, 3)
    target_pairs = ['Inr-MTE', 'TATA-Inr', 'TATA-MTE', 'DPE-MTE', 'TATA-BRE', 'TATA-DPE']
    colors = ['green', 'blue', 'purple', 'darkorange', 'red', 'brown']

    for pair, color in zip(target_pairs, colors):
        key, positions = resolve_pair(real_synergy['tss_positions'], pair)
        if key and len(positions) > 1 and len(set(positions)) > 1:
            sns.kdeplot(positions, ax=ax3, label=key, color=color, linewidth=2)

    ax3.axvline(0, color='black', linestyle=':', label='TSS (0)')
    ax3.set_xlim(-1000, 0)
    ax3.set_xlabel('Position Relative to TSS (bp)')
    ax3.set_ylabel('Pair Density Peak')
    ax3.set_title('C. Pair Co-occurrence Density Peak near TSS (Figure 5 Peak)')
    ax3.legend(fontsize=8, loc='upper left')
    ax3.grid(True, linestyle=':', alpha=0.6)

    # Subplot D: Pairwise Distance Spacing Distribution (bp)
    ax4 = fig.add_subplot(2, 2, 4)
    for pair, color in zip(['Inr-MTE', 'TATA-Inr', 'TATA-DPE', 'TATA-BRE'], ['green', 'blue', 'brown', 'red']):
        key, dists = resolve_pair(real_synergy['distances'], pair)
        if key and len(dists) > 1 and len(set(dists)) > 1:
            sns.kdeplot(dists, ax=ax4, label=f"{key} Spacing", color=color, linewidth=2)

    ax4.set_xlim(0, 150)
    ax4.set_xlabel('Distance Between Element Pair (bp)')
    ax4.set_ylabel('Density')
    ax4.set_title('D. Inter-element Distance / Spacing Distribution')
    ax4.legend(fontsize=8)
    ax4.grid(True, linestyle=':', alpha=0.6)

    plt.tight_layout()
    plt.savefig(OUT_PLOT, dpi=300)
    plt.close()

    print(f"\n[✓] Analysis complete!")
    print(f"Synergism Plot saved -> {OUT_PLOT}")
    print(f"Report Summary saved -> {OUT_REPORT}")


if __name__ == "__main__":
    run_synergism_analysis()